#!/usr/bin/python3
"""Creates a module that factorizes various numbers
as products of two other numbers
"""

from sys import argv


def factorize(value):
	i = 2

	if value < 2:
		return
	print()
	print(value, "<- value-bef")
	while value % 1:
	    i += 1
	print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
	print(value, "<-value-aft")
	print()

if len(argv) != 2:
	exit()

try:
	with open(argv[1] as file:
		line = line.readline()

		while line != "":
			value = int(line.split('\n'[0])
			factorize(value)
			line = file.readline()

except:
	pass
